[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Adam Tibbing <adam@tibbing.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
ferris-says = "0.1.1"
regex = "1"